### ISSUE TITLE
Errors in the Sample code.

### ISSUE THREAD

**Issue by Gavin-Williams** [microsoft/CsWinRT#1053]
**Issue Summary**

When I load the sample 'CppWinRTComponentProjectionSample' and try to build SimpleMathComponent. I get 3 errors. One fix can be applied but the build still produced errors.

**To Reproduce**

1. Download zip for CsWinRT samples @ https://github.com/microsoft/CsWinRT
2. Extract and open CsWinRT-master / src / Samples / Net5ProjectionSample / CppWinRTComponentProjectionSample.sln
3. Build SimpleMathComponent

Build fails with the following 3 errors...

1) Path 'C:\Users\deads\Desktop\Dev\CsWinRT-master\src\Samples\Net5ProjectionSample\\_build\x64\Debug\SimpleMathComponent\bin\SimpleMathComponent\SimpleMathComponent.winmd' is not a file or directory	SimpleMathProjection	C:\Users\deads\Desktop\Dev\CsWinRT-master\src\Samples\Net5ProjectionSample\SimpleMathProjection\EXEC	1	

2) MSB3073	The command ""C:\Users\deads\.nuget\packages\microsoft.windows.cswinrt\1.2.6\cswinrt.exe" "C:\Users\deads\Desktop\Dev\CsWinRT-master\src\Samples\Net5ProjectionSample\\_build\x64\Debug\SimpleMathProjection\bin\cswinrt.rsp"" exited with code 1.	SimpleMathProjection	C:\Users\deads\.nuget\packages\microsoft.windows.cswinrt\1.2.6\build\Microsoft.Windows.CsWinRT.targets	109	

3) MSB8020	The build tools for Visual Studio 2019 (Platform Toolset = 'v142') cannot be found. To build using the v142 build tools, please install Visual Studio 2019 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution".	SimpleMathComponent	C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppBuild.targets	436	

SimpleMathComponent.dll and SimpleMathComponent.winmd do exist in...
"C:\Users\deads\Desktop\Dev\CsWinRT-master\src\Samples\Net5ProjectionSample\\_build\x64\Debug\SimpleMathComponent\bin\SimpleMathComponent"

But the error contradicts the evidence. Unless I'm reading those file paths wrong - they are doing my head in.

**Expected behavior**

I expect the C++ component to build at this stage. I have v143 (latest) build tools installed.

I can update the project to use the latest build tools as suggested in the error. This resolves just the one error. Now the project successfully builds but is still showing errors 1 and 2 as above. This is the same behavior I was seeing on my previous attempt to use this sample code. After changing the project to use the correct build tools I expect the project to build without errors.

It's unclear to me, if anything has actually worked at this point. Has it built successfully or not? The error reads that CsWinRT has exited with a failure, and that the file (that exists) isn't a file.

**Version Info**

Windows 11 Pro 21H2 (22000.318)
VS 2022 (17.0.1)
MSVC v143 (latest)
C++/WinRT
Windows 10 SDK (10.0.19041.0)
Windows 11 SDK (10.0.22000.0)
Windows App SDK C# VS2022 Templates
Windows App SDK C++ VS2022 Templates

**Comment by angelazhangmsft** [comment]
@Gavin-Williams, thanks for the feedback, I've opened #1054 to update the sample to .NET 6 and to set the startup project to *SimpleMathProjection* instead of *SimpleMathComponent*, which may have been causing confusion. However, a few things:

- Try cleaning all the output folders (Generated Files, bin/obj, Debug) and make sure the platform/configuration is set to x64/Debug.
- Instead of building *SimpleMathComponent*, first ensure that *SimpleMathProjection* is set as the startup project, and build the whole solution instead of the C++ component project. 
- If you are targeting .NET 6, you will need to upgrade to CsWinRT 1.3.3 or later.
- To check if the C# projection is successfully building, check that there is a nupkg file generated in the folder `SimpleMathProjection/nuget`. You can then open *ConsoleAppSample.sln* in VS and be able to successfully reference the nupkg, build, and run the console app.

**Comment by Gavin-Williams** [comment]
The nupkg file is in the nuget folder.

I still have 2 warnings and 2 errors though.

** Warnings **

(1) Warning CS0169	The field 'IReferenceTrackerTargetVftbl._Peg' is never used	SimpleMathProjection	C:\Users\deads\Desktop\Dev\CsWinRT-master\src\Samples\Net5ProjectionSample\_build\x64\Debug\SimpleMathProjection\bin\WinRT_Interop.cs	47

(2) Warning	CS0169	The field 'IReferenceTrackerTargetVftbl._Unpeg' is never used	SimpleMathProjection	C:\Users\deads\Desktop\Dev\CsWinRT-master\src\Samples\Net5ProjectionSample\_build\x64\Debug\SimpleMathProjection\bin\WinRT_Interop.cs	48

** Errors **

(1) Error		Path 'C:\Users\deads\Desktop\Dev\CsWinRT-master\src\Samples\Net5ProjectionSample\_build\x64\Debug\SimpleMathComponent\bin\SimpleMathComponent\SimpleMathComponent.winmd' is not a file or directory	SimpleMathProjection	C:\Users\deads\Desktop\Dev\CsWinRT-master\src\Samples\Net5ProjectionSample\SimpleMathProjection\EXEC	1

(2)  Error	MSB3073	The command ""C:\Users\deads\.nuget\packages\microsoft.windows.cswinrt\1.4.1\cswinrt.exe" @"C:\Users\deads\Desktop\Dev\CsWinRT-master\src\Samples\Net5ProjectionSample\_build\x64\Debug\SimpleMathProjection\bin\cswinrt.rsp"" exited with code 1.	SimpleMathProjection	C:\Users\deads\.nuget\packages\microsoft.windows.cswinrt\1.4.1\build\Microsoft.Windows.CsWinRT.targets	121

**Comment by angelazhangmsft** [comment]
@Gavin-Williams - I am now seeing the same warnings and errors when upgrading from 1.3.5 to 1.4.1. We will investigate some more.

For the following error, this is happening because of a breaking change in C#/WinRT 1.4.1: #1051. You will need to wait for the December .NET SDK update to be able to consume these projections, so I would recommend using 1.3.5 until then.

> Error CS1705 Assembly 'SimpleMathProjection' with identity 'SimpleMathProjection, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' uses 'WinRT.Runtime, Version=1.4.0.0, Culture=neutral, PublicKeyToken=99ea127f02d97709' which has a higher version than referenced assembly 'WinRT.Runtime' with identity 'WinRT.Runtime, Version=1.3.0.0, Culture=neutral, PublicKeyToken=99ea127f02d97709' ConsoleAppSample C:\Users\deads\Desktop\Dev\CsWinRT-master\src\Samples\Net5ProjectionSample\ConsoleAppSample\CSC 1

**Comment by angelazhangmsft** [comment]
I've opened #1056 to track the errors. Looks like an issue with Visual Studio designer build, but the projection can still be built successfully. The warnings are expected and will be removed in a future CsWinRT release.

As for this error:

> Error	NETSDK1130	SimpleMathComponent.winmd cannot be referenced. Referencing a Windows Metadata component directly when targeting .NET 5 or higher is not supported. For more information, see https://aka.ms/netsdk1130	ConsoleAppSample	C:\Program Files\dotnet\sdk\6.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets	1003	

This will not occur if the console app only has a package reference to the component.

**Comment by Gavin-Williams** [comment]
"This will not occur if the console app only has a package reference to the component." What do you mean by that? How else could the component be referenced? Is this something I can fix?

**Comment by angelazhangmsft** [comment]
Sorry for the late reply - the recommendation is to have a package reference to the component. You could also use a project reference, but that requires adding a reference to the CsWinRT package in the app as a workaround for the NETSDK1130 error.

**Comment by Gavin-Williams** [comment]
Thanks for following up. I've actually given up on the approach I was going to take - making a graphics library with language interop for running C++/DirectX from C#. I think the situation is that some of this stuff is new, and it's all quite fragile and MS need to do a lot of work around setup and tooling. And the current design for C#/C++ interop is very time consuming and involved. Especially for someone like me, working by myself. I'm fine programming in C# and a little in C++. But once I have to deal with all this other stuff like xml files, and dll's, and linking projects manually with file-paths, I quickly get bogged down and find it hard to get stuff to work.

I liked the old style of adding a project reference by clicking a check box. Anything beyond that is just too much work. I've been trying to get this stuff working in my spare time for a few months now without any real success. I did manage to get a runtime component working C++ to C++ but that was as far as I got. I'm finding the next step to get C++/C# interop working just too convoluted.

I'm going to do this next project in Unity. I just can't spend time on this stuff right now. I really hope the tooling and overall design of interop gets some serious work done on it. Maybe I can revisit it late next year. What I really want is for it to be as easy as adding a project or library reference in C#. It shouldn't be complicated. I really hope the current design is just a consequence of timing, and that all this will just go away, and it will be automated.
